export const channelIDs = [
  {name: "Dokibird", channelId: "UComInW10MkHJs-_vi4rHQCQ"},
  {name: "HololiveEN", channelId: "UCotXwY6s8pWmuWd_snKYjhg"},
  {name: "Pekora", channelId: "UC1DCedRgGHBdm81E1llLhOQ"},
  {name: "Bae", channelId: "UCgmPnx-EEeOrZSg5Tiw7ZRQ"},
  {name: "Bijou", channelId: "UC9p_lqQ0FEDz327Vgf5JwqA"},
  {name: "Marine", channelId: "UCCzUftO8KOVkV4wQG1vkUvg"},
  {name: "Calli", channelId: "UCL_qhgtOy0dy1Agp8vkySQg"},
  {name: "Nerissa", channelId: "UC_sFNM0z0MWm9A6WlKPuMMg"},
  {name: "Kobo", channelId: "UCjLEmnpCNeisMxy134KPwWw"},
  {name: "Nimi", channelId: "UCIfAvpeIWGHb0duCkMkmm2Q"},
  {name: "Shiori", channelId: "UCgnfPPb9JI3e9A4cXHnWbyg"},
  {name: "Dooby", channelId: "UC6T7TJZbW6nO-qsc5coo8Pg"},
  {name: "Maid Mint", channelId: "UCcHHkJ98eSfa5aj0mdTwwLQ"},
  {name: "Cecilia", channelId: "UCvN5h1ShZtc7nlo3pezRayg"},
  {name: "Hajime", channelId: "UC1iA6_NT4mtAcIII6ygrvCw"},
  {name: "ERB", channelId: "UCW5uhrG1eCBYditmhL0Ykjw"},
  {name: "Zeta", channelId: "UCTvHWSfBZgtxE4sILOaurIQ"},
  {name: "Okayu", channelId: "UCvaTdHTWBGv3MKj3KVqJVCw"},
  {name: "Kiara", channelId: "UCHsx4Hqa-1ORjQTh9TYDhww"},
  {name: "Kronii", channelId: "UCmbs8T6MWqUHP1tIQvSgKrg"},
  {name: "Gigi", channelId: "UCDHABijvPBnJm7F-KlNME3w"},
  {name: "Elite Miko", channelId: "UC-hM6YJuNYVAmUWxeIr9FeA"},
  {name: "Kaela", channelId: "UCZLZ8Jjx_RN2CXloOmgTHVg"},
  {name: "iRyS", channelId: "UC8rcEBzJSleTkf_-agPM20g"},
  {name: "Ina", channelId: "UCMwGHR0BTZuLsmjY_NT5Pwg"},
  {name: "Laplus", channelId: "UCENwRMx5Yh42zWpzURebzTw"},
  {name: "Towa", channelId: "UC1uv2Oq6kNxgATlCiez59hw"},
  {name: "Suisei", channelId: "UC5CwaMl1eIgY8h02uZw7u8A"},
  {name: "Korone", channelId: "UChAnqc_AY5_I3Px5dig3X1Q"},
  {name: "Saba", channelId: "UCxsZ6NCzjU_t4YSxQLBcM5A"},
  {name: "Raora", channelId: "UCl69AEx4MdqMZH7Jtsm7Tig"},
  {name: "Fuwamoco", channelId: "UCt9H_RpQzhxzlyBxFqrdHqA"},
  {name: "Ollie", channelId: "UCYz_5n-uDuChHtLo7My1HnQ"},
  {name: "Shachi", channelId: "UCuBEdI-24bquMoP_dACignQ"}
];
